version: '3.8'

services:
  web:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      SECRET_KEY: ${SECRET_KEY:-default_secret_key}  # Use environment variable or default