"""Default migration message

Revision ID: 77677efa46ea
Revises: 0367674a9f77
Create Date: 2024-05-03 14:44:32.784318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77677efa46ea'
down_revision = '0367674a9f77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('online', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('taskgiver_id', sa.Integer(), nullable=False),
    sa.Column('taskacceptor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['taskacceptor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['taskgiver_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('user')
    # ### end Alembic commands ###
